export enum UserActivityType {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_COMPLETE = 'PASSWORD_RESET_COMPLETE',

  PROFILE_UPDATE = 'PROFILE_UPDATE',
  AVATAR_UPDATE = 'AVATAR_UPDATE',
  EMAIL_UPDATE = 'EMAIL_UPDATE',
  PHONE_UPDATE = 'PHONE_UPDATE',

  REGISTRATION = 'REGISTRATION',
  ACCOUNT_CREATED = 'ACCOUNT_CREATED',
  ACCOUNT_DEACTIVATED = 'ACCOUNT_DEACTIVATED',
  ACCOUNT_ACTIVATED = 'ACCOUNT_ACTIVATED',
  ACCOUNT_DELETED = 'ACCOUNT_DELETED',

  ROLE_CHANGE = 'ROLE_CHANGE',
  SECURITY_ALERT = 'SECURITY_ALERT',
  TWO_FACTOR_ENABLED = 'TWO_FACTOR_ENABLED',
  TWO_FACTOR_DISABLED = 'TWO_FACTOR_DISABLED',
}
