export enum AuthenticationErrorCode {
  EMAIL_ALREADY_TAKEN = 'EMAIL_ALREADY_TAKEN',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
  CREDENTIALS_NOT_FOUND = 'CREDENTIALS_NOT_FOUND',
  INVALID_CURRENT_PASSWORD = 'INVALID_CURRENT_PASSWORD',
  RESET_TOKEN_INVALID = 'RESET_TOKEN_INVALID',
  RESET_TOKEN_EXPIRED = 'RESET_TOKEN_EXPIRED',
}
