export enum NotificationErrorCode {
  EMAIL_SEND_FAILED = 'NOTIFICATION_EMAIL_SEND_FAILED',
  SMS_SEND_FAILED = 'NOTIFICATION_SMS_SEND_FAILED',
  TEMPLATE_NOT_FOUND = 'NOTIFICATION_TEMPLATE_NOT_FOUND',
  TEMPLATE_RENDER_FAILED = 'NOTIFICATION_TEMPLATE_RENDER_FAILED',
  INVALID_PAYLOAD = 'NOTIFICATION_INVALID_PAYLOAD',
}
