export enum IdentityErrorCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_CREATE_FAILED = 'USER_CREATE_FAILED',
  USER_UPDATE_FAILED = 'USER_UPDATE_FAILED',
  USER_DELETE_FAILED = 'USER_DELETE_FAILED',
  USER_QUERY_FAILED = 'USER_QUERY_FAILED',

  USER_PROFILE_NOT_FOUND = 'USER_PROFILE_NOT_FOUND',
  USER_PROFILE_UPDATE_FAILED = 'USER_PROFILE_UPDATE_FAILED',

  INVALID_BULK_OPERATION = 'INVALID_BULK_OPERATION',

  REQUIRE_PERSON = 'REQUIRE_PERSON',
}
